
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Adjust usernamer, password, and host.
  username: postgres 
  password: password
  host: localhost

development:
  <<: *default
  database: literbug2_development

test:
  <<: *default
  database: literbug2_test

production:
  <<: *default
  database: literbug2_production
  # Comment out username and password
  # username: literbug2
  # password: <%= ENV['LITERBUG2_DATABASE_PASSWORD'] %>
